global:
  resolve_timeout: 1m
  # slack_api_url: 'https://hooks.slack.com/services/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'
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  # receiver: 'gmail-notifications'
  receiver: 'slack-notifications'

receivers:
# - name: 'gmail-notifications'
#   email_configs:
#   - to: ananddubey016@gmail.com
#     from: ananddubey016@gmail.com
#     smarthost: smtp.gmail.com:587
#     auth_username: ananddubey016@gmail.com
#     auth_identity: ananddubey016@gmail.com
#     auth_password: 
#     send_resolved: true

- name: 'slack-notifications'
  slack_configs:
  - channel: '#testing'
    send_resolved: true
    icon_url: https://avatars3.githubusercontent.com/u/3380462
    title: |-
     [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
     {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
       {{" "}}(
       {{- with .CommonLabels.Remove .GroupLabels.Names }}
         {{- range $index, $label := .SortedPairs -}}
           {{ if $index }}, {{ end }}
           {{- $label.Name }}="{{ $label.Value -}}"
         {{- end }}
       {{- end -}}
       )
     {{- end }}
    text: >-
     {{ range .Alerts -}}
     *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

     *Description:* {{ .Annotations.description }}

     *Details:*
       {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
       {{ end }}
     {{ end }}

    # https://api.slack.com/apps/A032WPKFCDN/